"""empty message

Revision ID: 395aebedbe9c
Revises: f9f4101548b1
Create Date: 2022-02-05 22:38:09.013846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395aebedbe9c'
down_revision = 'f9f4101548b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=256), nullable=False),
    sa.Column('Nickname', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=256), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
