"""empty message

Revision ID: 67c8fb3a640b
Revises: e44a98691908
Create Date: 2022-02-06 20:41:58.857356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67c8fb3a640b'
down_revision = 'e44a98691908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('nickname', sa.String(length=20), nullable=False))
    op.drop_column('link', 'Nickname1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('Nickname1', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('link', 'nickname')
    # ### end Alembic commands ###
