"""empty message

Revision ID: e44a98691908
Revises: 395aebedbe9c
Create Date: 2022-02-06 20:38:14.749314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e44a98691908'
down_revision = '395aebedbe9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('nickname', sa.String(length=20), nullable=False))
    op.drop_column('link', 'Nickname')
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('archivo', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'archivo')
    op.drop_column('post', 'created')
    op.add_column('link', sa.Column('Nickname', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('link', 'nickname')
    # ### end Alembic commands ###
