"""empty message

Revision ID: f9f4101548b1
Revises: d110811b63ac
Create Date: 2022-02-02 21:17:01.994505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f4101548b1'
down_revision = 'd110811b63ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sci_user', sa.Column('nickname', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sci_user', 'nickname')
    # ### end Alembic commands ###
